/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assignment4.ui;

import assignment4.model.Community;
import assignment4.model.Encounter;
import assignment4.model.Patient;
import assignment4.model.PatientDirectory;
import assignment4.model.Person;
import assignment4.model.VitalSigns;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EncounterPanel extends javax.swing.JPanel {
    private PatientDirectory patientDir;
    private Patient curPatient;
    /**
     * Creates new form EncounterPanel
     */
    public EncounterPanel(PatientDirectory patientDirectory) {
        this.patientDir = patientDirectory;
        initComponents();
        patientCBox.removeAllItems();
        
        for (Patient p: patientDirectory.getPatients()) {
            patientCBox.addItem(p.getPerson().getName());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        encounterTable = new javax.swing.JTable();
        patientCBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        doctorText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sbpText = new javax.swing.JTextField();
        dbpText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        heartRateText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        temperatureText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spo2Text = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        encounterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient", "Doctor", "BP", "Heart Rate", "Temperature", "SPO2", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(encounterTable);

        patientCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientCBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Patient - ");

        jLabel2.setText("Doctor ");

        jLabel3.setText("Systolic Blood Pressure");

        dbpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbpTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Diastolic Blood Pressure");

        jLabel5.setText("Heart Rate");

        jLabel6.setText("Temperature");

        jLabel7.setText("Blood Oxygen Level");

        addButton.setText("Add New Encounter");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update Selected Encounter");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete Selected Encounter");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(temperatureText, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(heartRateText, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(dbpText, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(doctorText)
                            .addComponent(sbpText, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(spo2Text)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(patientCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(doctorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sbpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dbpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(heartRateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(temperatureText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(spo2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(deleteButton)
                    .addComponent(updateButton))
                .addContainerGap(183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void patientCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientCBoxActionPerformed
        // TODO add your handling code here:
        int idx = patientCBox.getSelectedIndex();
        if (idx < 0)
            return;
        Patient patient = patientDir.getPatients().get(idx);
        curPatient = patient;
        populateEncountersTable(patient);
    }//GEN-LAST:event_patientCBoxActionPerformed

    private void dbpTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbpTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbpTextActionPerformed

    private Encounter parseEncounter() {
        Encounter enc = new Encounter();
        VitalSigns vt = new VitalSigns();
        
        if (enc.setDoctor(doctorText.getText().trim()) == false) {
            JOptionPane.showMessageDialog(this, "Doctor is not in the correct format.");
            return null;
        }
        
        if (vt.setSbp(sbpText.getText().trim()) == false) {
            JOptionPane.showMessageDialog(this, "Systolic Blood Pressure is not in the correct format.");
            return null;
        }
        
        if (vt.setDbp(dbpText.getText().trim()) == false) {
            JOptionPane.showMessageDialog(this, "Diastolic Blood Pressure is not in the correct format.");
            return null;
        }
        
        if (vt.setHeartRate(heartRateText.getText().trim()) == false) {
            JOptionPane.showMessageDialog(this, "Heart Rate is not in the correct format.");
            return null;
        }
        
        if (vt.setTemperature(temperatureText.getText().trim()) == false) {
            JOptionPane.showMessageDialog(this, "Temperature is not in the correct format.");
            return null;
        }
        
        if (vt.setSpo2(spo2Text.getText().trim()) == false) {
            JOptionPane.showMessageDialog(this, "Blood Oxygen Level is not in the correct format.");
            return null;
        }
        
        enc.setVitalSigns(vt);
        return enc;
    }
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        Encounter enc = parseEncounter();
        if (enc == null) 
            return;
        
        if(curPatient.getEncounterHistory().addEncounter(enc)) {
            JOptionPane.showMessageDialog(this, "Encounter added successfully.");
            populateEncountersTable(curPatient);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = encounterTable.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to be deleted.");
            return;
        }
        
        Encounter enc = (Encounter) encounterTable.getValueAt(selectedRow, 6);
        if(curPatient.getEncounterHistory().deleteEncounter(enc)){
            JOptionPane.showMessageDialog(this, "Selected encounter was deleted.");
        }
        else{
            return;
        }

        populateEncountersTable(curPatient);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = encounterTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to be updated.");
            return;
        }
        
        Encounter enc = parseEncounter();
        if (enc == null) 
            return;
        
        curPatient.getEncounterHistory().updateEncounter(selectedRow, enc);
        JOptionPane.showMessageDialog(this, "Encounter updated successfully.");
        populateEncountersTable(curPatient);
    }//GEN-LAST:event_updateButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField dbpText;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField doctorText;
    private javax.swing.JTable encounterTable;
    private javax.swing.JTextField heartRateText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> patientCBox;
    private javax.swing.JTextField sbpText;
    private javax.swing.JTextField spo2Text;
    private javax.swing.JTextField temperatureText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    private void populateEncountersTable(Patient patient) {
        String patientName = patient.getPerson().getName();
        ArrayList<Encounter> encounterList = patient.getEncounterHistory().getEncounterList();
        DefaultTableModel model = (DefaultTableModel) encounterTable.getModel();
        model.setRowCount(0);
        for (Encounter e: encounterList) {
            Object[] row = new Object[7];
            row[0] = patientName;
            row[1] = e.getDoctor();
            VitalSigns vt = e.getVitalSigns();
            row[2] = ((int)vt.getDbp()) + "/" + ((int)vt.getSbp());
            row[3] = vt.getHeartRate();
            row[4] = vt.getTemperature();
            row[5] = vt.getSpo2();
            row[6] = e;
            model.addRow(row);
        }
    }
}
