/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment4.ui;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author geeth
 */
public class WelcomePanel extends javax.swing.JPanel {

    /**
     * Creates new form WelcomePanel
     */
    public WelcomePanel() {
        initComponents();
        
        imageOne.setIcon(new ImageIcon(new ImageIcon("imgs/bp_range.jpg").getImage(
                ).getScaledInstance(400, 300, Image.SCALE_DEFAULT)));
        imageTwo.setIcon(new ImageIcon(new ImageIcon("imgs/heart_rate_range.jpg").getImage(
                ).getScaledInstance(500, 300, Image.SCALE_DEFAULT)));
        
        imageThree.setIcon(new ImageIcon(new ImageIcon("imgs/spo2_range.jpg").getImage(
                ).getScaledInstance(400, 300, Image.SCALE_DEFAULT)));
        imageFour.setIcon(new ImageIcon(new ImageIcon("imgs/temp_range.jpg").getImage(
                ).getScaledInstance(500, 300, Image.SCALE_DEFAULT)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imageOne = new javax.swing.JLabel();
        imageTwo = new javax.swing.JLabel();
        imageThree = new javax.swing.JLabel();
        imageFour = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 253, 223));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Health Monitoring Application");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imageTwo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageThree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imageFour)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageOne)
                    .addComponent(imageTwo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageThree)
                    .addComponent(imageFour))
                .addContainerGap(427, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageFour;
    private javax.swing.JLabel imageOne;
    private javax.swing.JLabel imageThree;
    private javax.swing.JLabel imageTwo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
