/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.RestaurantAdminRole;

import Business.Restaurant.MenuItem;
import Business.Restaurant.Restaurant;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ManageMenu extends javax.swing.JPanel {

    private JPanel container;
    private Restaurant rest;

    /**
     * Creates new form ManageMenu
     */
    public ManageMenu(JPanel container, Restaurant rest) {
        initComponents();
        this.container = container;
        this.rest = rest;
        
        menuTable.setShowHorizontalLines(true);
        menuTable.setShowVerticalLines(true);
        populateMenuTable();
    }
    
    public void populateMenuTable() {
        DefaultTableModel model = (DefaultTableModel) menuTable.getModel();
        model.setRowCount(0);
        for (MenuItem mi : rest.getMenu()) {
            Object[] row = new Object[2];
            row[0] = mi.getName();
            row[1] = mi.getCost();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();
        addDishButton = new javax.swing.JButton();
        updateDishButton = new javax.swing.JButton();
        removeDishButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        backButton.setBackground(new java.awt.Color(0, 0, 51));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 204));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Manage Menu");

        menuTable.setBackground(new java.awt.Color(255, 255, 204));
        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Dish Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(menuTable);

        jLabel2.setText("Dish Name : ");

        jLabel3.setText("Price : ");

        addDishButton.setBackground(new java.awt.Color(0, 0, 51));
        addDishButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addDishButton.setForeground(new java.awt.Color(255, 255, 204));
        addDishButton.setText("Add Dish");
        addDishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDishButtonActionPerformed(evt);
            }
        });

        updateDishButton.setBackground(new java.awt.Color(0, 0, 51));
        updateDishButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updateDishButton.setForeground(new java.awt.Color(255, 255, 204));
        updateDishButton.setText("Update Dish");
        updateDishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDishButtonActionPerformed(evt);
            }
        });

        removeDishButton.setBackground(new java.awt.Color(0, 0, 51));
        removeDishButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        removeDishButton.setForeground(new java.awt.Color(255, 255, 204));
        removeDishButton.setText("Remove Dish");
        removeDishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(updateDishButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(removeDishButton))
                                            .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(addDishButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backButton)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDishButton)
                    .addComponent(updateDishButton)
                    .addComponent(removeDishButton))
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backButtonActionPerformed

    private MenuItem parseMenuItem() {
        MenuItem mi = new MenuItem();
        
        if (mi.setName(nameText.getText()) == false) {
            JOptionPane.showMessageDialog(this, "Name is not in the correct format.");
            return null;
        }
        
        if (mi.setCost(priceText.getText()) == false) {
            JOptionPane.showMessageDialog(this, "Price is not in the correct format.");
            return null;
        }
        
        return mi;
    }
    
    
    private void addDishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDishButtonActionPerformed
        // TODO add your handling code here:
        MenuItem mi = parseMenuItem();
        
        if (mi == null)
            return;
        
        rest.getMenu().add(mi);
        JOptionPane.showMessageDialog(this, "New menu item added successfully.");
        populateMenuTable();
        clearFields();
    }//GEN-LAST:event_addDishButtonActionPerformed

    private void updateDishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDishButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = menuTable.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to be updated.");
            return;
        }
        
        MenuItem mi = parseMenuItem();
        if (mi == null)
            return;
        
        rest.getMenu().set(selectedRow, mi);
        JOptionPane.showMessageDialog(this, "Menu item updated successfully.");
        populateMenuTable();
        clearFields();
    }//GEN-LAST:event_updateDishButtonActionPerformed

    private void removeDishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDishButtonActionPerformed
        int selectedRow = menuTable.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to be deleted.");
            return;
        }
        
        rest.getMenu().remove(selectedRow);
        JOptionPane.showMessageDialog(this, "Menu item deleted successfully.");
        populateMenuTable();
    }//GEN-LAST:event_removeDishButtonActionPerformed
    
    private void clearFields() {
        nameText.setText("");
        priceText.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDishButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable menuTable;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField priceText;
    private javax.swing.JButton removeDishButton;
    private javax.swing.JButton updateDishButton;
    // End of variables declaration//GEN-END:variables
}
