package ui;

import javax.swing.JOptionPane;
import model.Car;
import model.CarType;
import model.Driver;
import model.MaintenanceCertificate;
import model.Uber;

public class AddCarPanel extends javax.swing.JPanel {

    private Uber uber;

    /**
     * Creates new form AddCarPanel
     */
    public AddCarPanel(Uber uber) {
        this.uber = uber;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carTypeGroup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        availableGroup = new javax.swing.ButtonGroup();
        genderButtonGroup = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        passengerRadioButton = new javax.swing.JRadioButton();
        commercialRadioButton = new javax.swing.JRadioButton();
        rentalRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        yesRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        driverNameText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        otherRadioButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        ageText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        manufacturerText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        manufactureYearText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        numSeatsText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        serialNumText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        modelNumberText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cityText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        certNumText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        validFromText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        validTillText = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jTextField1.setText("jTextField1");

        jLabel1.setText("Car Type");

        carTypeGroup.add(passengerRadioButton);
        passengerRadioButton.setText("Passenger");
        passengerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengerRadioButtonActionPerformed(evt);
            }
        });

        carTypeGroup.add(commercialRadioButton);
        commercialRadioButton.setText("Commercial");
        commercialRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commercialRadioButtonActionPerformed(evt);
            }
        });

        carTypeGroup.add(rentalRadioButton);
        rentalRadioButton.setText("Rental");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Create New Car");

        jLabel4.setText("Available");

        availableGroup.add(yesRadioButton);
        yesRadioButton.setText("Yes");

        availableGroup.add(noRadioButton);
        noRadioButton.setText("No");

        jLabel5.setText("Driver Name");

        driverNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverNameTextActionPerformed(evt);
            }
        });

        jLabel6.setText("Driver Gender");

        genderButtonGroup.add(maleRadioButton);
        maleRadioButton.setText("Male");

        genderButtonGroup.add(femaleRadioButton);
        femaleRadioButton.setText("Female");

        genderButtonGroup.add(otherRadioButton);
        otherRadioButton.setText("Other");

        jLabel7.setText("Driver Age");

        jLabel8.setText("Manufacturer");

        jLabel9.setText("Manufacture Year");

        jLabel10.setText("Number of Seats");

        jLabel11.setText("Serial Number");

        jLabel12.setText("Model Number");

        jLabel13.setText("City");

        jLabel14.setText("Maintenance Cert Num");

        jLabel15.setText("Cert Valid From");

        validFromText.setToolTipText("yyyy-MM-dd HH:mm:ss");

        jLabel16.setText("Cert Valid Till");

        validTillText.setToolTipText("yyyy-MM-dd HH:mm:ss");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maleRadioButton)
                                .addGap(50, 50, 50)
                                .addComponent(femaleRadioButton)
                                .addGap(48, 48, 48)
                                .addComponent(otherRadioButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yesRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(noRadioButton))
                            .addComponent(driverNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passengerRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(commercialRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rentalRadioButton))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manufacturerText)
                            .addComponent(manufactureYearText)
                            .addComponent(numSeatsText)
                            .addComponent(serialNumText)
                            .addComponent(modelNumberText)
                            .addComponent(cityText, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(certNumText)
                                .addComponent(validFromText)
                                .addComponent(validTillText, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(passengerRadioButton)
                    .addComponent(commercialRadioButton)
                    .addComponent(rentalRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(yesRadioButton)
                    .addComponent(noRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(driverNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(maleRadioButton)
                    .addComponent(femaleRadioButton)
                    .addComponent(otherRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(manufacturerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(manufactureYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(numSeatsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(serialNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(modelNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(certNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(validFromText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(validTillText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void passengerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passengerRadioButtonActionPerformed

    private void commercialRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commercialRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commercialRadioButtonActionPerformed

    private void driverNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverNameTextActionPerformed

    private boolean showMessageIfNotSet(boolean isSet, String fieldName) {
        if (isSet == false) 
            JOptionPane.showMessageDialog(this, fieldName + " is not valid.");
        return isSet;
    }
    
    private String getSelectedGender() {
        if(maleRadioButton.isSelected())
            return "Male";
        else if (femaleRadioButton.isSelected())
            return "Female";
        else if (otherRadioButton.isSelected())
            return "Other";
        else
            return "";
    }
    
    private CarType getCarType() {
        if(passengerRadioButton.isSelected()) {
            return CarType.PASSENGER;
        } else if (rentalRadioButton.isSelected()) 
            return CarType.RENTAL;
        else if (commercialRadioButton.isSelected())
            return CarType.COMMERCIAL;
        else
            return null;
    }
    
    private Boolean getAvailability() {
        if (yesRadioButton.isSelected())
            return true;
        else if (noRadioButton.isSelected())
            return false;
        else
            return null;
    }
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        Car car = new Car();
        Driver driver = new Driver();
        MaintenanceCertificate cert = new MaintenanceCertificate();
        
        if (showMessageIfNotSet(car.setCarType(getCarType()), "Car Type") == false)
            return;
        
        Boolean isAvailable = getAvailability();
        if (isAvailable == null) {
            JOptionPane.showMessageDialog(this, "Please mention the car availablity.");
            return;
        }
        car.setIsAvailable(isAvailable);
        
        if (showMessageIfNotSet(driver.setName(driverNameText.getText()), "Driver Name") == false)
            return;
 
        if (showMessageIfNotSet(driver.setGender(getSelectedGender()), "Gender") == false)
            return;
        
        if (showMessageIfNotSet(driver.setAge(ageText.getText()), "Age") == false)
            return;
        
        if (showMessageIfNotSet(car.setManufacturer(manufacturerText.getText()), "Manufacturer") == false)
            return;
        
        if (showMessageIfNotSet(car.setManufactureYear(manufactureYearText.getText()), "Manufacture Year") == false)
            return;
        
        if (showMessageIfNotSet(car.setNumSeats(numSeatsText.getText()), "Number of seats") == false)
            return;
        
        if (showMessageIfNotSet(car.setSerialNumber(serialNumText.getText()), "Serial Number") == false)
            return;
        
        if (showMessageIfNotSet(car.setModelNumber(modelNumberText.getText()), "Model Number") == false)
            return;
        
        if (showMessageIfNotSet(car.setCity(cityText.getText()), "City") == false)
            return;
        
        if (showMessageIfNotSet(cert.setCertificate(certNumText.getText()), "Maintenance Certificate Number") == false)
            return;
        
        if (showMessageIfNotSet(cert.setValidFromStr(validFromText.getText()), "Maintenance Certificate Valid From") == false){
            JOptionPane.showMessageDialog(this, "Certificate validity time format - yyyy-MM-dd HH:mm:ss");
            return;
        }
        
        if (showMessageIfNotSet(cert.setValidTillStr(validTillText.getText()), "Maintenance Certificate Valid Till") == false){
            JOptionPane.showMessageDialog(this, "Certificate validity time format - yyyy-MM-dd HH:mm:ss");
            return;
        }
        
        car.setDriver(driver);
        car.setMaintenanceCertificate(cert);
        
        uber.addCar(car);
        
        JOptionPane.showMessageDialog(this, "Car Information saved");
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageText;
    private javax.swing.ButtonGroup availableGroup;
    private javax.swing.ButtonGroup carTypeGroup;
    private javax.swing.JTextField certNumText;
    private javax.swing.JTextField cityText;
    private javax.swing.JRadioButton commercialRadioButton;
    private javax.swing.JTextField driverNameText;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JTextField manufactureYearText;
    private javax.swing.JTextField manufacturerText;
    private javax.swing.JTextField modelNumberText;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JTextField numSeatsText;
    private javax.swing.JRadioButton otherRadioButton;
    private javax.swing.JRadioButton passengerRadioButton;
    private javax.swing.JRadioButton rentalRadioButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField serialNumText;
    private javax.swing.JTextField validFromText;
    private javax.swing.JTextField validTillText;
    private javax.swing.JRadioButton yesRadioButton;
    // End of variables declaration//GEN-END:variables
}
