package ui;

import javax.swing.JScrollPane;
import model.Uber;

public class UberApp extends javax.swing.JFrame {

    private final Uber uber;
    private final int HEIGHT = 700;
    private final int WIDTH = 1300;

    /**
     * Creates new form UberApp
     */
    public UberApp() {
        initComponents();
        uber = new Uber("./data/car_fleet.csv");
        setSize(WIDTH, HEIGHT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        addCarsButton = new javax.swing.JButton();
        updateCarsButton = new javax.swing.JButton();
        viewCarsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftPanel.setBackground(new java.awt.Color(253, 253, 223));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        splitPanel.setRightComponent(leftPanel);

        rightPanel.setBackground(new java.awt.Color(253, 253, 223));

        addCarsButton.setBackground(new java.awt.Color(38, 55, 85));
        addCarsButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addCarsButton.setText("Add Car");
        addCarsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarsButtonActionPerformed(evt);
            }
        });

        updateCarsButton.setBackground(new java.awt.Color(38, 55, 85));
        updateCarsButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updateCarsButton.setText("Update Cars");
        updateCarsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCarsButtonActionPerformed(evt);
            }
        });

        viewCarsButton.setBackground(new java.awt.Color(38, 55, 85));
        viewCarsButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        viewCarsButton.setText("View Cars");
        viewCarsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCarsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateCarsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addComponent(viewCarsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(addCarsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(addCarsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateCarsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewCarsButton)
                .addContainerGap(377, Short.MAX_VALUE))
        );

        splitPanel.setLeftComponent(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCarsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarsButtonActionPerformed
        // TODO add your handling code here:
        splitPanel.setRightComponent(new JScrollPane(new AddCarPanel(uber)));
    }//GEN-LAST:event_addCarsButtonActionPerformed

    private void updateCarsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCarsButtonActionPerformed
        // TODO add your handling code here:
        splitPanel.setRightComponent(new JScrollPane(new UpdateCarsPanel(uber)));
    }//GEN-LAST:event_updateCarsButtonActionPerformed

    private void viewCarsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCarsButtonActionPerformed
        // TODO add your handling code here:
        splitPanel.setRightComponent(new JScrollPane(new ViewCarsPanel(uber)));
    }//GEN-LAST:event_viewCarsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UberApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UberApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UberApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UberApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UberApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCarsButton;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JSplitPane splitPanel;
    private javax.swing.JButton updateCarsButton;
    private javax.swing.JButton viewCarsButton;
    // End of variables declaration//GEN-END:variables
}
