/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import javax.swing.JOptionPane;
import model.Profile;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author geeth
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Profile profile;
    public CreateJPanel(Profile profile) {
        initComponents();
        this.profile = profile;
        setInitialValues(profile);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblGeoData = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblTelNum = new javax.swing.JLabel();
        lblFaxNum = new javax.swing.JLabel();
        lblEmailId = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        lblMedRecNum = new javax.swing.JLabel();
        lblHlthPlnBenNum = new javax.swing.JLabel();
        lblBnkAccNum = new javax.swing.JLabel();
        lblCrtLicNum = new javax.swing.JLabel();
        lblVclIdSlNumIncLicPl = new javax.swing.JLabel();
        lblDevIdSlNum = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        lblIpAdd = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        lblUniqueId = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtGeoData = new javax.swing.JTextField();
        txtFaxNum = new javax.swing.JTextField();
        txtTelNum = new javax.swing.JTextField();
        txtEmailId = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtMedRecNum = new javax.swing.JTextField();
        txtHlthPlnBenNum = new javax.swing.JTextField();
        txtBnkAccNum = new javax.swing.JTextField();
        txtCrtLicNum = new javax.swing.JTextField();
        txtVclIdSlNumIncLicPl = new javax.swing.JTextField();
        txtDevIdSlNum = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        txtIpAdd = new javax.swing.JTextField();
        txtUniqueId = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        pickFileButton = new javax.swing.JButton();
        pickedFileLabel = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Profile");

        lblName.setText("Name:");

        lblGeoData.setText("Geographical Data:");

        lblDob.setText("Date Of Birth:");

        lblTelNum.setText("Telephone Number:");

        lblFaxNum.setText("FAX Number:");

        lblEmailId.setText("Email Address:");

        lblSsn.setText("SSN:");

        lblMedRecNum.setText("Medical Record Number:");

        lblHlthPlnBenNum.setText("Health Plan Beneficiary Number:");

        lblBnkAccNum.setText("Bank Account Number:");

        lblCrtLicNum.setText("Certificate/License Number:");

        lblVclIdSlNumIncLicPl.setText("Vehicle Identifiers & Serial Number: ");

        lblDevIdSlNum.setText("Device Identifiers & Serial Number:");

        lblLinkedin.setText("Linkedin:");

        lblIpAdd.setText("Internet Protocol Address:");

        lblPhoto.setText("Photo/Image:");

        lblUniqueId.setText("Unique ID:");

        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });

        txtGeoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeoDataActionPerformed(evt);
            }
        });

        txtFaxNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNumActionPerformed(evt);
            }
        });

        txtTelNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelNumActionPerformed(evt);
            }
        });

        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });

        txtSsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSsnActionPerformed(evt);
            }
        });

        txtMedRecNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedRecNumActionPerformed(evt);
            }
        });

        txtHlthPlnBenNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHlthPlnBenNumActionPerformed(evt);
            }
        });

        txtBnkAccNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBnkAccNumActionPerformed(evt);
            }
        });

        txtCrtLicNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrtLicNumActionPerformed(evt);
            }
        });

        txtVclIdSlNumIncLicPl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVclIdSlNumIncLicPlActionPerformed(evt);
            }
        });

        txtDevIdSlNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDevIdSlNumActionPerformed(evt);
            }
        });

        txtLinkedin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedinActionPerformed(evt);
            }
        });

        txtIpAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIpAddActionPerformed(evt);
            }
        });

        txtUniqueId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniqueIdActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        pickFileButton.setText("Pick File");
        pickFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhoto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSsn)
                            .addComponent(lblIpAdd)
                            .addComponent(lblLinkedin)
                            .addComponent(lblDevIdSlNum)
                            .addComponent(lblVclIdSlNumIncLicPl)
                            .addComponent(lblCrtLicNum)
                            .addComponent(lblName)
                            .addComponent(lblMedRecNum)
                            .addComponent(lblHlthPlnBenNum)
                            .addComponent(lblEmailId)
                            .addComponent(lblFaxNum)
                            .addComponent(lblTelNum)
                            .addComponent(lblDob)
                            .addComponent(lblGeoData)
                            .addComponent(lblBnkAccNum))
                        .addComponent(lblUniqueId, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtIpAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(txtLinkedin, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDevIdSlNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVclIdSlNumIncLicPl, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCrtLicNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBnkAccNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHlthPlnBenNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMedRecNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSsn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmailId, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFaxNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDob, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGeoData, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pickFileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pickedFileLabel))
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUniqueId))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeoData)
                    .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDob)
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelNum)
                    .addComponent(txtTelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaxNum)
                    .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailId)
                    .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSsn)
                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedRecNum)
                    .addComponent(txtMedRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHlthPlnBenNum)
                    .addComponent(txtHlthPlnBenNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBnkAccNum)
                    .addComponent(txtBnkAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrtLicNum)
                    .addComponent(txtCrtLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVclIdSlNumIncLicPl)
                    .addComponent(txtVclIdSlNumIncLicPl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDevIdSlNum)
                    .addComponent(txtDevIdSlNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedin)
                    .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIpAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIpAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniqueId)
                    .addComponent(txtUniqueId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoto)
                    .addComponent(pickFileButton)
                    .addComponent(pickedFileLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed

    private void txtGeoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeoDataActionPerformed

    private void txtFaxNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNumActionPerformed

    private void txtTelNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelNumActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void txtSsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSsnActionPerformed

    private void txtMedRecNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedRecNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedRecNumActionPerformed

    private void txtHlthPlnBenNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHlthPlnBenNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHlthPlnBenNumActionPerformed

    private void txtBnkAccNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBnkAccNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBnkAccNumActionPerformed

    private void txtCrtLicNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrtLicNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrtLicNumActionPerformed

    private void txtVclIdSlNumIncLicPlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVclIdSlNumIncLicPlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVclIdSlNumIncLicPlActionPerformed

    private void txtDevIdSlNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDevIdSlNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDevIdSlNumActionPerformed

    private void txtLinkedinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedinActionPerformed

    private void txtIpAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIpAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIpAddActionPerformed

    private void txtUniqueIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniqueIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniqueIdActionPerformed

    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        boolean didItGetSet = profile.setName(txtName.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "Name is not valid");
            return;
        }
        
        didItGetSet = profile.setDob(txtDob.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "Date of Birth is not valid");
            return;
        }
        
        didItGetSet = profile.setGeoData(txtGeoData.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "Geographical Data is not valid");
            return;
        }
        
        didItGetSet = profile.setTelNum(txtTelNum.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "Telephone Number is not valid");
            return;
        }              
        
        //String telNumStr = txtTelNum.getText();
        //int telNumInt = Integer.parseInt(telNumStr);
        //profile.setTelNum(telNumInt);
        didItGetSet = profile.setFaxNum(txtFaxNum.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "Fax Number is not valid");
            return;
        }
        //String faxNumStr = txtFaxNum.getText();
        //int faxNumInt = Integer.parseInt(faxNumStr);
        //profile.setFaxNum(faxNumInt);
                       
        didItGetSet = profile.setEmailId(txtEmailId.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "Email ID is not valid");
            return;
        }
        
        didItGetSet = profile.setSsn(txtSsn.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "SSN is not valid");
            return;
        }
        
        didItGetSet = profile.setMedRecNum(txtMedRecNum.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "Medical Record Number is not valid");
            return;
        }
        
        didItGetSet = profile.setHlthPlnBenNum(txtHlthPlnBenNum.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "Health Plan Beneficiary Number is not valid");
            return;
        }
        
        //String bnkAccNum = txtBnkAccNum.getText();
        //int bnkAccNumInt = Integer.parseInt(bnkAccNum);
        didItGetSet = profile.setBnkAccNum(txtBnkAccNum.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "Bank Account Number is not valid");
            return;
        }
        
        didItGetSet = profile.setCrtLicNum(txtCrtLicNum.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "Certificate/License Number is not valid");
            return;
        }
        
        didItGetSet = profile.setVclIdSlNumIncLicPl(txtVclIdSlNumIncLicPl.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "Vehicle Identifiers & Serial Number is not valid");
            return;
        }
        
        didItGetSet = profile.setDevIdSlNum(txtDevIdSlNum.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "Device Identifiers & Serial Number is not valid");
            return;
        }
        
        didItGetSet = profile.setLinkedin(txtLinkedin.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "Linkedin is not valid");
            return;
        }
        
        didItGetSet = profile.setIpAdd(txtIpAdd.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "IP Address is not valid");
            return;
        }
        
        didItGetSet = profile.setUniqueId(txtUniqueId.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "Unique ID is not valid");
            return;
        }
        
        didItGetSet = profile.setImage(pickedFileLabel.getText());
        if (didItGetSet == false) {
            JOptionPane.showMessageDialog(this, "File path is not valid");
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Profile Information Saved.");
                     
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameFocusLost

    private void pickFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickFileButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileFilter(
              new FileNameExtensionFilter("Images", "jpg", "jpeg", "png", "gif", "bmp"));
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            pickedFileLabel.setText(fileChooser.getSelectedFile().toString());
        }
    }//GEN-LAST:event_pickFileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblBnkAccNum;
    private javax.swing.JLabel lblCrtLicNum;
    private javax.swing.JLabel lblDevIdSlNum;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblFaxNum;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHlthPlnBenNum;
    private javax.swing.JLabel lblIpAdd;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblMedRecNum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblTelNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUniqueId;
    private javax.swing.JLabel lblVclIdSlNumIncLicPl;
    private javax.swing.JButton pickFileButton;
    private javax.swing.JLabel pickedFileLabel;
    private javax.swing.JTextField txtBnkAccNum;
    private javax.swing.JTextField txtCrtLicNum;
    private javax.swing.JTextField txtDevIdSlNum;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtFaxNum;
    private javax.swing.JTextField txtGeoData;
    private javax.swing.JTextField txtHlthPlnBenNum;
    private javax.swing.JTextField txtIpAdd;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMedRecNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtTelNum;
    private javax.swing.JTextField txtUniqueId;
    private javax.swing.JTextField txtVclIdSlNumIncLicPl;
    // End of variables declaration//GEN-END:variables

    private void setInitialValues(Profile profile) {
        txtName.setText(profile.getName());
        txtGeoData.setText(profile.getGeoData());
        txtDob.setText(profile.getDob());
        txtTelNum.setText(profile.getTelNum());
        txtFaxNum.setText(profile.getFaxNum());
        txtEmailId.setText(profile.getEmailId());
        txtSsn.setText(profile.getSsn());
        txtMedRecNum.setText(profile.getMedRecNum());
        txtHlthPlnBenNum.setText(profile.getHlthPlnBenNum());
        txtBnkAccNum.setText(profile.getBnkAccNum());
        txtCrtLicNum.setText(profile.getCrtLicNum());
        txtVclIdSlNumIncLicPl.setText(profile.getVclIdSlNumIncLicPl());
        txtDevIdSlNum.setText(profile.getDevIdSlNum());
        txtLinkedin.setText(profile.getLinkedin());
        txtIpAdd.setText(profile.getIpAdd());
        txtUniqueId.setText(profile.getUniqueId());
        
        File f = profile.getImage();
        if (f != null) 
            pickedFileLabel.setText(f.getPath().toString());
        
    }
}
